### ISSUE TITLE
Switch to Acorn

### ISSUE THREAD

**Issue by sindresorhus** [SBoudrias/AST-query#21]
It's faster, more actively maintained and got ES6 support.

https://github.com/marijnh/acorn

**Comment by sindresorhus** [comment]
@RReverser How difficult is it to switch?

**Comment by RReverser** [comment]
@sindresorhus Didn't look into code of AST-query too much, but since it's just about parsing, then should be extremely easy - just pay attention to option names.

**Comment by Grimace1975** [comment]
Added the option for Acorn, not a clean way of selection options with the API. could select option every place its used (entry, valueFactory, body)

**Comment by akalenda** [comment]
I notice there are commits saying that the parser was moved to Acorn, is this then a closed issue?

**Comment by SBoudrias** [comment]
Ah yes, it is indeed.
