### ISSUE TITLE
Parsing `export default`

### ISSUE THREAD

**Issue by lukemorton** [SBoudrias/AST-query#29]
Hi there,

I'm trying to parse an `export default` statement in order to append something to an array. Ideally I'd like the following to work:

```
program = require('ast-query');
tree = program('export default [];', {}, { sourceType: 'module' });
console.log(tree.push('item').toString());
```

However I get the following when trying to parse the program:

![screenshot 2016-03-06 09 49 30](https://cloud.githubusercontent.com/assets/272640/13553422/c60ea8aa-e380-11e5-912f-ecd3dd33fe31.png)

**Comment by SBoudrias** [comment]
Tests now fails on the latest master. Looks like esprima changed some stuff internally in a patch release. I've gone through their docs and couldn't find what we're doing wrong.

Feel free to investigate further, it's probably related to which options we pass to esprima - you might also want to directly test with esprima to make sure it's not a bug on their side.

**Comment by SBoudrias** [comment]
I believe this is fix in the latest release. Let me know

**Comment by lukemorton** [comment]
Sweet, will check it out in a bit.
