### ISSUE TITLE
'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by Cuilz** [SBoudrias/AST-query#36]
const str = 'import Vue  from 'vue'; .... export default xxx;';
when i use: program(str);
throw err: SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

**Comment by amnsss** [comment]
`astQuery(strip(code), {}, { sourceType: "module" });` 
sourceType defaults to "script" and will error when it finds import or export. Pass sourceType: "module" to get rid of these errors

**Comment by Cuilz** [comment]
Thanks!
